# Criar usuário 1
POST http://127.0.0.1:8000/user HTTP/1.1
content-type: application/json

{
	"CPF": 12345678910,
    "name": "Luiza",
    "phone_number": 2142365125,
    "email": "carmencmattos@gmail.com",
    "password": "Aurora",
    "active": true,
    "admin": true
}

#######################################
# Criar usuário 2
POST http://127.0.0.1:8000/user HTTP/1.1
content-type: application/json

{
    "id": 2,
    "nome": "teste2",
    "email": "teste@gmail.com",
    "senha": "1234"
}

#######################################
# Criar usuário 3
POST http://127.0.0.1:8000/usuario HTTP/1.1
content-type: application/json

{
    "id": 3,
    "nome": "teste3",
    "email": "teste@gmail.com",
    "senha": "1234"
}


#######################################
# Pegar usuário pelo id
GET http://127.0.0.1:8000/usuario/3 HTTP/1.1
content-type: application/json


#######################################
# Pegar usuário pelo nome
GET http://127.0.0.1:8000/usuario?nome=teste1 HTTP/1.1
content-type: application/json


#######################################
# Deletar usuário pelo id
DELETE http://127.0.0.1:8000/usuario/3 HTTP/1.1
content-type: application/json


########################################
# Criar endereço
POST http://127.0.0.1:8000/endereco/ HTTP/1.1
content-type: application/json

{
    "id_usuario": 2,
    "rua": "Rua Luiza Code",
    "cep": "99999-888",
    "cidade": "Rio de Janeiro",
    "estado": "RJ"
}